routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Mevinda225150409111012Controller;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('mahasiswa', Mevinda225150409111012Controller::class);
Route::resource('article', WebController::class);

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/mevinda_225150409111012.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class mevinda_225150409111012 extends Model
{
    use HasFactory;
    protected $table = "mevinda_225150409111012s";
    protected $primaryKey = 'id';
    protected $fillable =
    [
        'nim',
        'nama'
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Mevinda225150409111012Controller.php
<?php

namespace App\Http\Controllers;

use App\Models\mevinda_225150409111012;
use App\Http\Requests\Storemevinda_225150409111012Request;
use App\Http\Requests\Updatemevinda_225150409111012Request;
use Illuminate\Http\Request;

class Mevinda225150409111012Controller extends Controller
{
   /**
     * Display a listing of the resource.
     */
    public function index()
    {
        // $mahasiswas = mahasiswa::where("alamat", "like", '%riau%')->get();
        // $mahasiswas = mahasiswa::where('alamat', 'like', '%riau%')->orWhere('alamat', 'like', '%mojokerto%')
        //     ->get();
        $mahasiswas = Mevinda_225150409111012::get();

        return view("index", ["mahasiswas" => $mahasiswas]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view("create");
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $mahasiswa = new Mevinda_225150409111012;
        $mahasiswa->nim = $request->nim;
        $mahasiswa->nama = $request->nama;
        $mahasiswa->save();

        return redirect()->route('mahasiswa.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Mevinda_225150409111012 $mahasiswa)
    {
        return "tampilan untuk detail data mahasiswa";
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Mevinda_225150409111012 $mahasiswa)
    {
        return view("edit", [
            "mahasiswa" => $mahasiswa
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Mevinda_225150409111012 $mahasiswa)
    {
        // aksi untuk mengupdate data mahasiswa
        $mahasiswa->nim = $request->nim;
        $mahasiswa->nama = $request->nama;
        $mahasiswa->save();

        return redirect()->route('mahasiswa.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Mevinda_225150409111012 $mahasiswa)
    {
        $mahasiswa->delete();

        return redirect()->route('mahasiswa.index');
    }
}

resources/views/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Create Data Mahasiswa</title>
</head>
<body>
    <h1>Tambah Data Mahasiswa</h1>
    <form action="{{ route('mahasiswa.store') }}" method="POST">
        @csrf
        <label for="nim">NIM</label>
        <input type="text" name="nim" id="nim">
        <br>
        <label for="nama">Nama</label>
        <input type="text" name="nama" id="nama">
        <br>
        <br>
        <a href="{{ route('mahasiswa.index')}}">Kembali</a>
        <button type="submit">Simpan</button>
</body>
</html>

resources/views/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Edit Data Mahasiswa</h1>
    <form action="{{ route('mahasiswa.update', $mahasiswa) }}" method="POST">
        @csrf
        @method('PUT')
        <label for="nim">NIM</label>
        <input type="text" name="nim" id="nim" value="{{ $mahasiswa->nim }}">
        <br>
        <label for="nama">Nama</label>
        <input type="text" name="nama" id="nama" value="{{ $mahasiswa->nama }}">
        <br>
        <a href="{{ route('mahasiswa.index')}}">Kembali</a>
        <button type="submit">Simpan</button>
</body>
</html>

resources/views/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Tabel Data Mahasiswa</h1>
    <a href="{{ route('mahasiswa.create') }}">Tambah</a>
    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>NIM</th>
                <th>Nama</th>
                <th>Aksi</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($mahasiswas as $mahasiswa)
            <tr>
                <td>{{ $mahasiswa->id }}</td>
                <td>{{ $mahasiswa->nim}}</td>
                <td>{{ $mahasiswa->nama}}</td>
                <td>
                    <a href="{{ route('mahasiswa.edit',$mahasiswa)}}">Edit</a>
                    <form action="{{ route('mahasiswa.destroy',$mahasiswa)}}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit">Hapus</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>